import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:uuid/uuid.dart';

import '../../shared/models/department_model.dart';
import '../../shared/models/member_model.dart';
import '../../shared/models/role_models.dart';
import 'lubumbashi_branding_service.dart';
import 'media_firestore_constants.dart';
import 'media_lists_local_repository.dart';
import 'permission_service.dart';
import 'smart_media_list_engine.dart';

/// Schedules and runs Sunday auto-list generation for media department (Lubumbashi).
class DepartmentListAutomationService {
  DepartmentListAutomationService({
    FirebaseFirestore? firestore,
    SmartMediaListEngine? listEngine,
    PermissionService? permissionService,
    MediaListsLocalRepository? localRepo,
    Uuid? uuid,
  })  : _firestore = firestore ?? FirebaseFirestore.instance,
        _engine = listEngine ?? SmartMediaListEngine(),
        _permissions = permissionService ?? PermissionService(),
        _localRepo = localRepo ?? MediaListsLocalRepository(),
        _uuid = uuid ?? const Uuid();

  final FirebaseFirestore _firestore;
  final SmartMediaListEngine _engine;
  final PermissionService _permissions;
  final MediaListsLocalRepository _localRepo;
  final Uuid _uuid;

  static const Duration defaultScheduleLead = Duration(days: 3);

  CollectionReference<Map<String, dynamic>> get _listsRef =>
      _firestore.collection(MediaFirestoreCollections.lists);

  CollectionReference<Map<String, dynamic>> get _membersRef =>
      _firestore.collection(MediaFirestoreCollections.members);

  CollectionReference<Map<String, dynamic>> get _rolesRef =>
      _firestore.collection(MediaFirestoreCollections.roles);

  /// Returns next Sunday date at midnight local.
  DateTime nextSunday({DateTime? from}) {
    final base = from ?? DateTime.now();
    var cursor = DateTime(base.year, base.month, base.day);
    while (cursor.weekday != DateTime.sunday) {
      cursor = cursor.add(const Duration(days: 1));
    }
    if (!cursor.isAfter(base)) {
      cursor = cursor.add(const Duration(days: 7));
    }
    return cursor;
  }

  bool shouldGenerateNow({DateTime? now}) {
    final current = now ?? DateTime.now();
    final target = nextSunday(from: current);
    final leadDate = target.subtract(defaultScheduleLead);
    return !current.isBefore(leadDate) && current.isBefore(target);
  }

  /// Generates and persists the auto Sunday list if not already present.
  Future<MediaSundayList?> runScheduledGeneration({
    required UserRole actor,
    DateTime? serviceDate,
    bool force = false,
  }) async {
    if (!_permissions.canManageMediaFirestore(actor) && !force) {
      throw StateError('Permission refusée: génération automatique.');
    }

    final sunday = serviceDate ?? nextSunday();
    if (!force && !shouldGenerateNow()) return null;

    final existing = await _findExistingAutoList(sunday);
    if (existing != null) return existing;

    final members = await _loadMembers();
    final roleMap = await _loadRoleMap();
    final list = _engine.generateSundayList(
      sundayDate: sunday,
      members: members,
      roleByMemberId: roleMap,
      listId: _uuid.v4(),
    );

    await _localRepo.saveList(
      list,
      extra: {
        'createdBy': actor.uid,
        'departmentId': 'media',
      },
    );
    try {
      await _listsRef.doc(list.id).set({
        ...list.toMap(),
        'createdBy': actor.uid,
        'departmentId': 'media',
        'scheduledAt': FieldValue.serverTimestamp(),
      });
    } catch (_) {
      // Local + queue — sync arrière-plan.
    }
    return list;
  }

  Future<MediaSundayList?> _findExistingAutoList(DateTime sunday) async {
    final dayStart = DateTime(sunday.year, sunday.month, sunday.day);
    final dayEnd = dayStart.add(const Duration(days: 1));
    final snap = await _listsRef
        .where('isAutoGenerated', isEqualTo: true)
        .where('serviceDate', isGreaterThanOrEqualTo: dayStart.toIso8601String())
        .where('serviceDate', isLessThan: dayEnd.toIso8601String())
        .limit(1)
        .get();
    if (snap.docs.isEmpty) return null;
    final doc = snap.docs.first;
    return MediaSundayList.fromMap(doc.data(), id: doc.id);
  }

  Future<List<Member>> _loadMembers() async {
    try {
      final snap = await _membersRef
          .where('departmentId', isEqualTo: Member.mediaDepartmentId)
          .where('isActive', isEqualTo: true)
          .get();
      if (snap.docs.isNotEmpty) {
        return snap.docs
            .map((d) => Member.fromMap(d.data(), id: d.id))
            .toList();
      }
    } catch (_) {}
    return const [];
  }

  Future<Map<String, MediaRole>> _loadRoleMap() async {
    try {
      final snap = await _rolesRef.get();
      final map = <String, MediaRole>{};
      for (final doc in snap.docs) {
        final assignment = MediaRoleAssignment.fromMap(doc.data());
        map[assignment.memberId] = assignment.mediaRole;
      }
      return map;
    } catch (_) {
      return {};
    }
  }
}
