import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:uuid/uuid.dart';

import '../../shared/models/department_model.dart';
import '../../shared/models/role_models.dart';
import 'lubumbashi_branding_service.dart';
import 'media_firestore_constants.dart';
import 'media_lists_local_repository.dart';
import 'permission_service.dart';

/// CRUD for manual Sunday media lists (Lubumbashi).
class ManualListManager {
  ManualListManager({
    FirebaseFirestore? firestore,
    PermissionService? permissionService,
    MediaListsLocalRepository? localRepo,
    Uuid? uuid,
  })  : _firestore = firestore ?? FirebaseFirestore.instance,
        _permissions = permissionService ?? PermissionService(),
        _localRepo = localRepo ?? MediaListsLocalRepository(),
        _uuid = uuid ?? const Uuid();

  final FirebaseFirestore _firestore;
  final PermissionService _permissions;
  final MediaListsLocalRepository _localRepo;
  final Uuid _uuid;

  CollectionReference<Map<String, dynamic>> get _listsRef =>
      _firestore.collection(MediaFirestoreCollections.lists);

  Future<MediaSundayList> create({
    required UserRole actor,
    required DateTime serviceDate,
    required List<MediaListEntry> entries,
  }) async {
    _ensureCanManage(actor);
    final id = _uuid.v4();
    final list = MediaSundayList(
      id: id,
      serviceDate: serviceDate,
      entries: entries,
      isAutoGenerated: false,
      isManual: true,
      city: LubumbashiBrandingService.city,
      createdAt: DateTime.now(),
    );
    await _localRepo.saveList(
      list,
      extra: {'createdBy': actor.uid, 'departmentId': 'media'},
    );
    try {
      await _listsRef.doc(id).set({
        ...list.toMap(),
        'createdBy': actor.uid,
        'departmentId': 'media',
      });
    } catch (_) {
      // Sync en file d'attente via SQLite — pas d'erreur UI.
    }
    return list;
  }

  Future<MediaSundayList> read(String listId) async {
    final doc = await _listsRef.doc(listId).get();
    if (!doc.exists) {
      throw StateError('Liste introuvable: $listId');
    }
    return MediaSundayList.fromMap(doc.data()!, id: doc.id);
  }

  Future<MediaSundayList> update({
    required UserRole actor,
    required String listId,
    DateTime? serviceDate,
    List<MediaListEntry>? entries,
  }) async {
    _ensureCanManage(actor);
    final existing = await read(listId);
    final updated = MediaSundayList(
      id: listId,
      serviceDate: serviceDate ?? existing.serviceDate,
      entries: entries ?? existing.entries,
      isAutoGenerated: false,
      isManual: true,
      city: LubumbashiBrandingService.city,
      createdAt: existing.createdAt,
      updatedAt: DateTime.now(),
    );
    await _listsRef.doc(listId).update({
      ...updated.toMap(),
      'updatedBy': actor.uid,
    });
    return updated;
  }

  Future<void> delete({
    required UserRole actor,
    required String listId,
  }) async {
    _ensureCanManage(actor);
    await _listsRef.doc(listId).delete();
  }

  Stream<List<MediaSundayList>> watchManualLists({int limit = 50}) {
    return _listsRef
        .where('isManual', isEqualTo: true)
        .where('city', isEqualTo: LubumbashiBrandingService.city)
        .orderBy('serviceDate', descending: true)
        .limit(limit)
        .snapshots()
        .map((snap) => snap.docs
            .map((d) => MediaSundayList.fromMap(d.data(), id: d.id))
            .toList());
  }

  Future<List<MediaSundayList>> listForMonth(int year, int month) async {
    final start = DateTime(year, month, 1);
    final end = DateTime(year, month + 1, 1);
    final snap = await _listsRef
        .where('isManual', isEqualTo: true)
        .where('serviceDate', isGreaterThanOrEqualTo: start.toIso8601String())
        .where('serviceDate', isLessThan: end.toIso8601String())
        .get();
    return snap.docs
        .map((d) => MediaSundayList.fromMap(d.data(), id: d.id))
        .toList();
  }

  void _ensureCanManage(UserRole actor) {
    if (!_permissions.canManageMediaFirestore(actor)) {
      throw StateError('Permission refusée: gestion des listes média.');
    }
  }
}
