import 'dart:typed_data';

import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../../shared/models/attendance_model.dart';
import '../../shared/models/department_model.dart';
import 'lubumbashi_branding_service.dart';
import 'professional_pdf_template.dart';
import 'text_sanitizer_service.dart';

/// PDF export for media attendance and Sunday lists (Lubumbashi).
class MediaPdfExportService {
  MediaPdfExportService({
    ProfessionalPdfTemplate? template,
  }) : _template = template ?? ProfessionalPdfTemplate();

  final ProfessionalPdfTemplate _template;

  Future<Uint8List> exportAttendanceReport({
    required String title,
    required List<MediaAttendanceRecord> records,
    required Map<String, String> memberNames,
  }) async {
    final doc = pw.Document();
    final page = await _template.buildDocument(
      listTitle: PdfSafeText.clean(title),
      departmentName: LubumbashiBrandingService.mediaDepartmentLabel,
      headers: const [
        'N°',
        'Nom complet',
        'Date',
        'Statut',
        'Session',
        'Notes',
      ],
      rows: records.asMap().entries.map((e) {
        final r = e.value;
        return [
          '${e.key + 1}',
          memberNames[r.memberId] ?? r.memberId,
          _formatDate(r.date),
          r.status.label,
          r.sessionType.label,
          r.notes ?? '',
        ];
      }).toList(),
    );
    doc.addPage(page);
    return doc.save();
  }

  Future<Uint8List> exportSundayList({
    required MediaSundayList list,
  }) async {
    final doc = pw.Document();
    final page = await _template.buildDocument(
      listTitle: list.isAutoGenerated
          ? 'Liste automatique du dimanche'
          : 'Liste manuelle du dimanche',
      departmentName: LubumbashiBrandingService.mediaDepartmentLabel,
      date: list.serviceDate,
      headers: const ['N°', 'Nom complet', 'Rôle Média', 'Notes'],
      rows: list.entries.map((e) {
        return [
          '${e.sortOrder + 1}',
          e.memberName,
          e.mediaRole,
          e.notes ?? '',
        ];
      }).toList(),
      signatureLabel: 'Responsable Média',
    );
    doc.addPage(page);
    return doc.save();
  }

  Future<void> printPdf(Uint8List bytes, {String name = 'ifcm_media'}) {
    return Printing.layoutPdf(
      onLayout: (format) async => bytes,
      name: '${LubumbashiBrandingService.csvHeaderPrefix}_$name.pdf',
    );
  }

  Future<void> sharePdf(Uint8List bytes, {String name = 'ifcm_media'}) {
    return Printing.sharePdf(
      bytes: bytes,
      filename: '${LubumbashiBrandingService.csvHeaderPrefix}_$name.pdf',
    );
  }

  String _formatDate(DateTime date) {
    return '${date.day.toString().padLeft(2, '0')}/${date.month.toString().padLeft(2, '0')}/${date.year}';
  }
}

typedef PdfExportService = MediaPdfExportService;
