import '../../shared/models/department_model.dart';
import '../../shared/models/member_model.dart';
import '../../shared/models/role_models.dart';
import 'lubumbashi_branding_service.dart';

/// Auto-generates Sunday media team lists based on roles and rotation (Lubumbashi).
class SmartMediaListEngine {
  SmartMediaListEngine({this.rotationWeeks = 4});

  final int rotationWeeks;

  static const List<MediaRole> _sundayRotationRoles = [
    MediaRole.camera,
    MediaRole.son,
    MediaRole.projection,
    MediaRole.streaming,
    MediaRole.photographe,
    MediaRole.montage,
    MediaRole.assistant,
  ];

  /// Builds a [MediaSundayList] for the given service [sundayDate].
  MediaSundayList generateSundayList({
    required DateTime sundayDate,
    required List<Member> members,
    required Map<String, MediaRole> roleByMemberId,
    String? listId,
  }) {
    final normalizedSunday = _normalizeSunday(sundayDate);
    final weekIndex = _weekRotationIndex(normalizedSunday);
    final activeMembers = members
        .where((m) => m.isActive && m.departmentId == Member.mediaDepartmentId)
        .toList();

    final entries = <MediaListEntry>[];
    var sortOrder = 0;

    final chef = _pickForRole(
      activeMembers,
      roleByMemberId,
      MediaRole.chefMedia,
    );
    if (chef != null) {
      entries.add(_entry(chef, MediaRole.chefMedia, sortOrder++));
    }

    final pointage = _pickForRole(
      activeMembers,
      roleByMemberId,
      MediaRole.operateurPointage,
    );
    if (pointage != null) {
      entries.add(_entry(pointage, MediaRole.operateurPointage, sortOrder++));
    }

    final usedIds = entries.map((e) => e.memberId).toSet();

    for (var i = 0; i < _sundayRotationRoles.length; i++) {
      final role = _sundayRotationRoles[i];
      final pool = activeMembers
          .where((m) => !usedIds.contains(m.id))
          .where((m) => roleByMemberId[m.id] == role)
          .toList();
      if (pool.isEmpty) continue;

      final index = (weekIndex + i) % pool.length;
      final selected = pool[index];
      entries.add(_entry(selected, role, sortOrder++));
      usedIds.add(selected.id);
    }

    return MediaSundayList(
      id: listId ?? 'auto_${normalizedSunday.millisecondsSinceEpoch}',
      serviceDate: normalizedSunday,
      entries: entries,
      isAutoGenerated: true,
      isManual: false,
      city: LubumbashiBrandingService.city,
      createdAt: DateTime.now(),
    );
  }

  Member? _pickForRole(
    List<Member> members,
    Map<String, MediaRole> roleByMemberId,
    MediaRole role,
  ) {
    try {
      return members.firstWhere((m) => roleByMemberId[m.id] == role);
    } catch (_) {
      return null;
    }
  }

  MediaListEntry _entry(Member member, MediaRole role, int sortOrder) {
    return MediaListEntry(
      memberId: member.id,
      memberName: member.name,
      mediaRole: role.name,
      notes: 'Rotation auto — ${LubumbashiBrandingService.city}',
      sortOrder: sortOrder,
    );
  }

  DateTime _normalizeSunday(DateTime date) {
    final weekday = date.weekday;
    final daysUntilSunday = DateTime.sunday - weekday;
    final sunday = date.add(Duration(days: daysUntilSunday));
    return DateTime(sunday.year, sunday.month, sunday.day);
  }

  int _weekRotationIndex(DateTime sunday) {
    final epoch = DateTime(2024, 1, 7);
    final weeks = sunday.difference(epoch).inDays ~/ 7;
    return weeks % rotationWeeks;
  }
}
