/// Department models for IFCM Lubumbashi.
library;

class Department {
  const Department({
    required this.id,
    required this.name,
    required this.code,
    this.description,
    this.city = 'Lubumbashi',
    this.chiefMemberId,
    this.isActive = true,
  });

  final String id;
  final String name;
  final String code;
  final String? description;
  final String city;
  final String? chiefMemberId;
  final bool isActive;

  factory Department.fromMap(Map<String, dynamic> map, {String? id}) {
    return Department(
      id: id ?? map['id'] as String? ?? '',
      name: map['name'] as String? ?? '',
      code: map['code'] as String? ?? '',
      description: map['description'] as String?,
      city: map['city'] as String? ?? 'Lubumbashi',
      chiefMemberId: map['chiefMemberId'] as String?,
      isActive: map['isActive'] as bool? ?? true,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'code': code,
      if (description != null) 'description': description,
      'city': city,
      if (chiefMemberId != null) 'chiefMemberId': chiefMemberId,
      'isActive': isActive,
    };
  }
}

/// Predefined media department for IFCM Lubumbashi.
class MediaDepartment {
  static const String id = 'media';
  static const String code = 'MEDIA';
  static const String name = 'Département Média';
  static const String city = 'Lubumbashi';

  static const Department instance = Department(
    id: id,
    name: name,
    code: code,
    description:
        'Équipe média IFCM — caméra, son, projection, streaming et photographe (Lubumbashi).',
    city: city,
    isActive: true,
  );

  static Department fromMap(Map<String, dynamic> map) {
    return Department.fromMap({
      ...map,
      'id': map['id'] ?? id,
      'name': map['name'] ?? name,
      'code': map['code'] ?? code,
      'city': map['city'] ?? city,
    });
  }
}

/// Sunday service list entry for media team rotation.
class MediaListEntry {
  const MediaListEntry({
    required this.memberId,
    required this.memberName,
    required this.mediaRole,
    this.notes,
    this.sortOrder = 0,
  });

  final String memberId;
  final String memberName;
  final String mediaRole;
  final String? notes;
  final int sortOrder;

  factory MediaListEntry.fromMap(Map<String, dynamic> map) {
    return MediaListEntry(
      memberId: map['memberId'] as String? ?? '',
      memberName: map['memberName'] as String? ?? '',
      mediaRole: map['mediaRole'] as String? ?? '',
      notes: map['notes'] as String?,
      sortOrder: map['sortOrder'] as int? ?? 0,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'memberId': memberId,
      'memberName': memberName,
      'mediaRole': mediaRole,
      if (notes != null) 'notes': notes,
      'sortOrder': sortOrder,
    };
  }
}

class MediaSundayList {
  const MediaSundayList({
    required this.id,
    required this.serviceDate,
    required this.entries,
    this.isAutoGenerated = true,
    this.isManual = false,
    this.city = 'Lubumbashi',
    this.createdAt,
    this.updatedAt,
  });

  final String id;
  final DateTime serviceDate;
  final List<MediaListEntry> entries;
  final bool isAutoGenerated;
  final bool isManual;
  final String city;
  final DateTime? createdAt;
  final DateTime? updatedAt;

  factory MediaSundayList.fromMap(Map<String, dynamic> map, {String? id}) {
    final entriesRaw = map['entries'] as List<dynamic>? ?? [];
    return MediaSundayList(
      id: id ?? map['id'] as String? ?? '',
      serviceDate: DateTime.tryParse(map['serviceDate']?.toString() ?? '') ??
          DateTime.now(),
      entries: entriesRaw
          .map((e) => MediaListEntry.fromMap(Map<String, dynamic>.from(e as Map)))
          .toList(),
      isAutoGenerated: map['isAutoGenerated'] as bool? ?? true,
      isManual: map['isManual'] as bool? ?? false,
      city: map['city'] as String? ?? 'Lubumbashi',
      createdAt: DateTime.tryParse(map['createdAt']?.toString() ?? ''),
      updatedAt: DateTime.tryParse(map['updatedAt']?.toString() ?? ''),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'serviceDate': serviceDate.toIso8601String(),
      'entries': entries.map((e) => e.toMap()).toList(),
      'isAutoGenerated': isAutoGenerated,
      'isManual': isManual,
      'city': city,
      if (createdAt != null) 'createdAt': createdAt!.toIso8601String(),
      if (updatedAt != null) 'updatedAt': updatedAt!.toIso8601String(),
    };
  }
}
