import 'package:uuid/uuid.dart';

import '../../../shared/models/department_model.dart';
import '../../services/media_lists_local_repository.dart';
import '../models/smart_models.dart';

/// Persiste la planification Média du dimanche dans les listes locales.
class SundayListPersistenceService {
  SundayListPersistenceService({
    MediaListsLocalRepository? lists,
    Uuid? uuid,
  })  : _lists = lists ?? MediaListsLocalRepository(),
        _uuid = uuid ?? const Uuid();

  final MediaListsLocalRepository _lists;
  final Uuid _uuid;

  Future<MediaSundayList> persistPlan(SundayTeamPlan plan) async {
    final entries = <MediaListEntry>[];
    var order = 0;
    for (final post in plan.posts) {
      if (post.assignedMemberId == null) continue;
      entries.add(
        MediaListEntry(
          memberId: post.assignedMemberId!,
          memberName: post.assignedMemberName ?? 'Membre',
          mediaRole: post.label,
          sortOrder: order++,
        ),
      );
    }

    final list = MediaSundayList(
      id: _uuid.v4(),
      serviceDate: plan.serviceDate,
      entries: entries,
      isAutoGenerated: true,
      isManual: false,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    await _lists.saveList(list, extra: {'departmentId': 'media', 'source': 'smart_planner'});
    return list;
  }
}
